# Generated by Django 5.2.16 on 2026-07-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityauditlog',
            name='event_type',
            field=models.CharField(choices=[('SHARE_CREATED', 'Share created'), ('SHARE_UPDATED', 'Share updated'), ('SHARE_REVOKED', 'Share revoked'), ('PROJECT_MEMBER_ADDED', 'Project member added'), ('PROJECT_MEMBER_UPDATED', 'Project member updated'), ('PROJECT_MEMBER_REMOVED', 'Project member removed'), ('COMMENT_DELETED', 'Comment deleted'), ('PUBLICATION_PUBLISHED', 'Publication published'), ('PUBLICATION_WITHDRAWN', 'Publication withdrawn')], max_length=40),
        ),
    ]
