# Generated by Django 5.2.16 on 2026-07-17 02:20

import app.accounts.models
from django.db import migrations, models
from django.utils.text import slugify


def populate_public_slugs(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    for profile in UserProfile.objects.select_related("user").filter(public_slug=None):
        base = slugify(profile.user.username, allow_unicode=True) or f"researcher-{profile.user_id}"
        candidate = base[:140]
        suffix = 2
        while UserProfile.objects.filter(public_slug=candidate).exclude(pk=profile.pk).exists():
            candidate = f"{base[:135]}-{suffix}"
            suffix += 1
        profile.public_slug = candidate
        profile.save(update_fields=("public_slug",))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, upload_to=app.accounts.models.profile_avatar_upload_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_scholar_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.RunPython(populate_public_slugs, migrations.RunPython.noop),
    ]
