# Generated by Django 5.2.16 on 2026-07-17 02:20

import app.publications.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research_objects', '0003_stage3_search_relations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_slug', models.SlugField(allow_unicode=True, max_length=220)),
                ('title', models.CharField(max_length=240)),
                ('summary', models.TextField(blank=True, max_length=600)),
                ('content_markdown', models.TextField(blank=True)),
                ('content_html', models.TextField(blank=True, editable=False)),
                ('metadata_json', models.JSONField(blank=True, default=dict, editable=False)),
                ('public_project_name', models.CharField(blank=True, max_length=160)),
                ('public_project_summary', models.TextField(blank=True, max_length=600)),
                ('cover_image', models.FileField(blank=True, upload_to=app.publications.models.snapshot_cover_upload_path)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_snapshots', to=settings.AUTH_USER_MODEL)),
                ('source_object', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='publication_snapshot', to='research_objects.researchobject')),
            ],
            options={
                'ordering': ('-published_at', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='PublishedAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=app.publications.models.public_attachment_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_attachments', to='publications.publicationsnapshot')),
                ('source_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_copies', to='research_objects.attachment')),
            ],
            options={
                'ordering': ('original_name',),
            },
        ),
        migrations.AddIndex(
            model_name='publicationsnapshot',
            index=models.Index(fields=['owner', 'is_published', '-published_at'], name='publication_owner_i_a2fd2e_idx'),
        ),
        migrations.AddConstraint(
            model_name='publicationsnapshot',
            constraint=models.UniqueConstraint(fields=('owner', 'public_slug'), name='unique_publication_slug_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='publishedattachment',
            constraint=models.UniqueConstraint(fields=('snapshot', 'source_attachment'), name='unique_public_copy_per_source_attachment'),
        ),
    ]
